### ISSUE TITLE
IM BLACK

### ISSUE THREAD

**Issue by Scripted1337** [TrolledTooMuch/Guilded-Server-Botter#1]

**Comment by TrolledTooMuch** [comment]
ur resps r sad

**Comment by Scripted1337** [comment]
lmfao

**Comment by Scripted1337** [comment]
your fucking guilded gen is blatantly skidded from my gen

**Comment by Scripted1337** [comment]
the methods are the same

**Comment by Scripted1337** [comment]
just made the code look bigger 🤡

**Comment by TrolledTooMuch** [comment]
tfym "the methods are the same" LOL

**Comment by Scripted1337** [comment]
https://i.imgur.com/fFK3wvf.png
https://i.imgur.com/z5HhXg9.png

**Comment by TrolledTooMuch** [comment]
what else am i supposed to do LOL, if i tried joining without doing anything it else it said "user needs to be logged in" r u sped

**Comment by Scripted1337** [comment]
never said that

**Comment by TrolledTooMuch** [comment]
then what are u on abt

**Comment by Scripted1337** [comment]
https://i.imgur.com/jiSkbUr.png

**Comment by Scripted1337** [comment]
ok.

**Comment by TrolledTooMuch** [comment]
accidentally closed hold on

**Comment by TrolledTooMuch** [comment]
nvm faggot
